### ISSUE TITLE
config.rabbitmq.yaml is not valid ddev configuration

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-rabbitmq#1]
DDEV will read `.ddev/config.rabbitmq.yaml` as configuration and try to merge it into ddev config... but it's not valid configuration. I assume this is intended for some other consumer? Maybe create a rabbitmq directory and put it there?

**Comment by ochorocho** [comment]
How to convert the `config.rabbitmq.yaml` to be a ddev config?

**Comment by rfay** [comment]
The problem you have right now is that you're *using* it in the ddev config space. Don't do that. If it has to be named that try to put it in another directory, for example .ddev/rabbitmq. Right now, DDEV will read it (and ignore everything there) because it's in .ddev/config.rabbitmq.yaml.

**Comment by ochorocho** [comment]
OK, gotcha.

**Comment by ochorocho** [comment]
Done. Thank you!
