### ISSUE TITLE
PCNTL required?

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-rabbitmq#5]
I happened to see this in the site I added rabbitmq to:

`Extension [PCNTL](http://php.net/pcntl) not present in PHP. Option rabbitmq_timeout is not available in the RabbitMQ consumer.`

<img width="1171" alt="image" src="https://github.com/ochorocho/ddev-rabbitmq/assets/112444/677f464c-0503-43b3-95f5-52da09a52acd">

Does the config.rabbitmq.yaml (when converted to be ddev config) need to have `webimage_extra_packages: [php8.x-pcntl]` or something?

**Comment by ochorocho** [comment]
I was not aware of this requirement. Sounds like it makes sense to add this to `webimage_extra_packages`.

**Comment by ochorocho** [comment]
According to the comment here, https://github.com/ochorocho/ddev-rabbitmq/issues/1#issuecomment-1783337472

How to add a package to `webimage_extra_packages`?  :-)

**Comment by rfay** [comment]
You would add a `config.rabbitmq.yaml` with
```
webimage_extra_packages: [php8.<x>-pcntl]`
```

Using that technique I don't know how to get the right PHP version without installing lots of them. As a custom Dockerfile (.ddev/web-build/Dockerfile.rabbitmq) it can use an environment variable $DDEV_PHP_VERSION, https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

**Comment by ochorocho** [comment]
Tested with these php version:
```
$ php8.1  -i | grep pcntl
pcntl
pcntl support => enabled

$ php8.2 -i | grep pcntl
pcntl
pcntl support => enabled

$ php8.3 -i | grep pcntl
pcntl
pcntl support => enabled

```

Seems like php8.x ships with `pcntl` enabled by default.

`extension_loaded('pcntl')` returns empty, and `phpinfo()` does not show pcntl enabled.
From what i read it is disabled for php-fpm.

Happy to enable it, if you can tell me just how? :-)

**Comment by rfay** [comment]
You're the expert here :) It's quite possible that the Drupal module either has a command-line approach that uses pcntl or it's just silly. I don't even know what pcntl is. I also don't know what rabbitmq is :)

**Comment by ochorocho** [comment]
I'll leave this open until i know more about rabbitmq and it's php requirements.

**Comment by ochorocho** [comment]
Did some research. pcntl is only needed on cli, at least this is what i have found:

* https://github.com/php/php-src/issues/12155#issuecomment-1711766233
* https://github.com/php-amqplib/RabbitMqBundle: For using command with this flag you need to install PHP with [PCNTL extension](http://www.php.net/manual/en/book.pcntl.php).

It now includes an additional test to see if pcntl is loaded on cli.

If you having problems on drupal feel free to re-open this issue.
