### ISSUE TITLE
Add simple demonstration setup to README?

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-rabbitmq#6]
Since many people (like me) are unfamiliar with RabbitMQ, would it make sense to either suggest a simple setup or link to one? The simple setup suggestion could be a gist, or perhaps a README in a subdirectory?

We'd probably all be interested to know how *you* as the maintainer use rabbitmq.

**Comment by ochorocho** [comment]
Yes, i want to use it in TYPO3 for testing purposes at the moment. We may use it in produciton at some point.
I'll try to provide a extension for TYPO3 as a example to start with.
